[package]
name = "ssm_gph"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.29.0", features = ["full"] }
aws-config = "0.55.3"
aws-sdk-ssm = "0.28.0"


